accounts/urls.py
from django.conf.urls.static import static
from django.contrib.auth.decorators import login_required
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from config import settings
from .views import *
from rest_framework.authtoken.views import obtain_auth_token
from django.contrib.auth import views as auth_views

app_name = 'accounts'
router = DefaultRouter()
router.register('accounts', UserCreateViewSet)

urlpatterns =[

    path('api-token-auth/', obtain_auth_token),
    path('rest-auth/', include('dj_rest_auth.urls')),
    path('rest-auth/registration/', include('dj_rest_auth.registration.urls')),
    path('allauth/', include('allauth.urls')),
    path('signup/', SignUpView, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('profile/detail/<str:username>/', ProfileView, name='profile'),
    path('profile/update/', profile_update, name='profile_update'),
    path('', include(router.urls)),

 ]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatapp/', include('chatapp.urls')),
    path('accounts/', include('accounts.urls')),
    path('location/', include('location.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from config import settings
from django.contrib.auth import get_user_model

class UserManager(BaseUserManager): # 유저 생성하는 헬퍼 클래스
    # 일반 user 생성
    def create_user(self, email, username, name, password=None):
        if not email:
            raise ValueError('must have user email')
        if not username:
            raise ValueError('must have user username')
        if not name:
            raise ValueError('must have user name')
        user = self.model(
            email=self.normalize_email(email),
            username=username,
            name=name
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    # 관리자 user 생성
    def create_superuser(self, email, username, name, password=None):
        user = self.create_user(
            email,
            password=password,
            username=username,
            name=name
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin): # 실제 모델을 상속받아 생성하는 클래스
    id = models.AutoField(primary_key=True)
    email = models.EmailField(default='', max_length=100, null=False, blank=False, unique=True)
    username = models.CharField(default='', max_length=100, null=False, blank=False, unique=True)
    name = models.CharField(default='', max_length=100, null=False, blank=False)

    # User 모델의 필수 field
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    date_joined = models.DateTimeField(auto_now_add=True)

    # 헬퍼 클래스 사용
    objects = UserManager()

    # 사용자의 username field는 username으로 설정
    USERNAME_FIELD = 'username'
    # 필수로 작성해야하는 field
    REQUIRED_FIELDS = ['email', 'name']

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 현 계정의 사용자를 가져올 수 있음.
    nickname = models.CharField(max_length=64)
    description = models.TextField(blank=True)
    profile_photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True) # 값을 채워넣지 않아도 되는 속성.

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm
from django.db import models
from .models import Profile

import accounts.models


class RegisterForm(forms.ModelForm):
    email = forms.EmailField(label="이메일")
    password = forms.CharField(label='비밀번호', widget=forms.PasswordInput)
    password2 = forms.CharField(label='비밀번호 확인', widget=forms.PasswordInput)

    class Meta:
        model = accounts.models.User
        fields = ['username', 'password', 'password2', 'email']
        labels = {
            'username': '아이디',
            'password': '비밀번호',
            'password2': '비밀번호 확인',
            'email': '이메일',
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('비밀번호 확인이 일치하지 않습니다.')
        return cd['password2']


class CustomUserChangeForm(UserChangeForm):
    password = None
    # UserChangeForm에서는 password를 수정할 수 없다.
    # 하지만 이렇게 None 값으로 지정해주지 않으면 password를 변경할 수 없다는 설명이 화면에 표현된다.
    class Meta:
        model = get_user_model()
        fields = ['email', 'username', 'name' ]


class ProfileForm(forms.ModelForm):
    nickname = forms.CharField(label="별명", required=False)
    description = forms.CharField(label="자기소개", required=False, widget=forms.Textarea())
    profile_photo = forms.ImageField(label="이미지", required=False)

    # 위의 내용을 정의하지 않아도 상관없지만, 화면에 출력될 때 label이 영문으로 출력되는 것이 싫어서 수정한 것이다..
    class Meta:
        model = Profile
        fields = ['nickname', 'description', 'profile_photo', ]

accounts/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import DetailView
from django.contrib import messages
from .forms import RegisterForm
from .serializers import CreateUserSerializer
from .models import User, Profile
from rest_framework.viewsets import ModelViewSet
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated
from django.shortcuts import get_object_or_404
from .forms import CustomUserChangeForm, ProfileForm


# 회원가입
# class UserCreate(generics.CreateAPIView):
class UserCreateViewSet(ModelViewSet):
    queryset = User.objects.all()
    serializer_class = CreateUserSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        serializer.save(author=self.request.user)

def SignUpView(request):
    if request.method == "POST":
        # 회원 가입 데이터 입력 완료
        user_form = RegisterForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'accounts/register_done.html', {'new_user': new_user})
    else:
        # 회원 가입 내용을 입력하는 상황
        user_form = RegisterForm()
    return render(request, 'accounts/signup.html', {'form' : user_form})


def ProfileView(request, username): # urls.py에서 넘겨준 인자를 username으로 받는다.
    if request.user.username == username:
        if not Profile.objects.filter(user=request.user):
            Profile.objects.create(user = request.user)
    person = get_object_or_404(get_user_model(), username=username)
    context = {'person':person, 'me': request.user}
    return render(request, 'accounts/profile.html', context)
# 프로필이 없으면 프로필 생성 페이지로 간다.
# 프로필이 있으면 프로필을 보여준다.

@login_required
def profile_update(request):
    user = get_object_or_404(Profile, user=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.profile_photo = request.POST.get('profile_photo')
            print(form.profile_photo)
            form.save()
            messages.success(request, '프로필을 수정/저장했습니다.')
            return redirect('accounts:profile', username=request.user)
    else:
        form = ProfileForm(instance=user)
    return render(request, 'accounts/profile_update.html', {
        'form': form
    })

templates/accounts/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row">
        <div class="col-4">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'accounts:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="#">
        {% csrf_token %}
        <input type="hidden" name="next" value="{{next}}"> <!-- 로그인 성공후 이동되는 URL -->
        {% include "form_errors.html" %}
        <div class="form-group">
            <lable for ="username">사용자ID</lable>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{form.username.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <lable for ="password">비밀번호</lable>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{form.password.value|default_if_none:''}}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/accounts/logout.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default">
            <div class="alert alert-info">로그아웃 하였습니다.</div>
            <a class="btn btn-primary" href="{% url 'accounts:login' %}">Click to Login</a>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

templates/accounts/profile.html
{% extends 'base.html' %}
{% block content %}
{% load static %}



<div class="row">
    <div class="col-xs-6 col-md-3">
        {% if person.profile.profile_photo %}
        <img class="round" src="{{user.profile.profile_photo.url}}" width="200"> <br>
        {% else %}
        <img class="round" src="{% static 'accounts/images/profile1.jpg' %}" width="200"> <br>
        {% endif %}
    </div>

    <div class="col-xs-6 col-md-3">
        {% if person.profile.nickname %}
        <h2>{{person.username}}</h2>
        {% endif %}
        {% if person == me %}   <!-- 로그인한 사용자와 profile_user(프로필 소유자)가 일치할 때만 프로필 편집이 가능하도록 함 -->
        <a href="{% url 'accounts:profile_update' %}">
            <button type="button" class="btn btn-default">프로필 편집</button></a></h2>
        {% endif %}
        <h3> 이름: {{person.profile.nickname}} <br></h3>
        <h3> 자기소개: {{person.profile.description}}</h3>


<!--        <h3>{{profile.profile.profile_photo}} </h3>-->
<!--        <img class="round" src="{{profile.profile.profile_photo.url}}" width="200"> <br>-->
    </div>
</div>
{% endblock %}

{% block script %}
<link rel="stylesheet" href="{% static 'accounts/style.css' %}">
{% endblock %}

templates/accounts/profile_update.html
<!-- templates/accounts/profile.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container">
    <div style="margin-top: 5rem !important;">
        <div class="col-12">

            <div class="row justify-content-center">
                <div class="card">
                    <div class="card-header" style="padding-bottom:8px;">
                        <strong style="font-size: 18px;"><i class="fas fa-user-edit"></i>&nbsp;&nbsp;내 정보수정</strong>
                    </div>
                    <div class="card-body">
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table style="color:black; margin-left:10px;">
                                <tr>
                                    <td class="profile_title">아이디</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user.username }}&nbsp;&nbsp;</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이메일</td>
                                    <td class="profile_content">&nbsp;&nbsp;{{ user.email }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">이름</td>
                                    <td class="profile_content">{{ form.nickname }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">자기소개</td>
                                    <td class="profile_content">{{ form.description }}</td>
                                </tr>
                                <tr>
                                    <td class="profile_title">프로필 사진</td>
                                    <td class="profile_content">{{ form.profile_photo }}</td>
                                </tr>
                            </table>
                            <br>
                            <div style="text-align: center; margin-bottom:-15px;">
                                <a onclick=location.href="{% url 'accounts:profile' username=user.username %}" class="btn btn-sm" id="back_btn"><i class="fa fa-reply"></i>&nbsp;돌아가기</a>
                                <button type="submit" class="btn btn-sm" id="detail_btn"><i class="fas fa-check"></i>&nbsp;수정하기</button>
                            </div>
                        </form>

                        <script type = "text/javascript">
                            function maxLengthCheck(object){
                                if (object.value.length > object.maxLength) {
                                    object.value = object.value.slice(0, object.maxLength);
                                    }
                                }
                        </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/register_done.html
{% extends 'base.html' %}
{% block title %} 회원가입 완 {% endblock %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default"> <!-- 합쳐서 12개가 되어야함 -->
            <div class="alert alert-info">회원가입이 완료되었습니다.</div>
            <a class="btn btn-info" href="/">메인화면으로 돌아가기</a>
            <a class="btn btn-primary" href="{% url 'accounts:login' %}">로그인 하기</a>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}

templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8 panel panel-default"> <!-- 합쳐서 12개가 되어야함 -->
            <div class="alert alert-info">회원 정보를 입력해주세요.</div>
            <form action="" method="post">
                {{form.as_p}}
                {% csrf_token %}
                <input class="btn btn-primary" type="submit" value="Sign up">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
{% endblock %}